//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
