//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class UCGrabEntities : DbContext
    {
        public UCGrabEntities()
            : base("name=UCGrabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<ContactUs> ContactUs { get; set; }
        public DbSet<Favorites> Favorites { get; set; }
        public DbSet<File_Documents> File_Documents { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<Image_Product> Image_Product { get; set; }
        public DbSet<Image_Store> Image_Store { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Order_Detail> Order_Detail { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<User_Accounts> User_Accounts { get; set; }
        public DbSet<User_Information> User_Information { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<vw_Role> vw_Role { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_getCartCountByUserId(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getCartCountByUserId", user_idParameter);
        }
    }
}
