//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UCGrabEntities : DbContext
    {
        public UCGrabEntities()
            : base("name=UCGrabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<ContactUs> ContactUs { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<Image_Product> Image_Product { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Order_Detail> Order_Detail { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User_Accounts> User_Accounts { get; set; }
        public DbSet<User_Information> User_Information { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<vw_Role> vw_Role { get; set; }
    }
}
