//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCGrab.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherUsage
    {
        public int id { get; set; }
        public Nullable<int> voucher_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> usage_date { get; set; }
    
        public virtual Vouchers Vouchers { get; set; }
    }
}
